version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'saturday'
    versioning-strategy: 'increase'
    pull-request-branch-name:
      separator: '-'
    commit-message:
      prefix: npm (prod)
      prefix-development: npm (dev)
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
